name: flutter_base
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.1.5 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  fluttertoast: ^8.2.4
  photo_view: ^0.14.0
  get: ^4.6.6
  flutter_localizations:
    sdk: flutter
  dio: ^5.4.1
  flutter_html: ^3.0.0-beta.2
  flutter_inappwebview: ^5.8.0
  device_info_plus: ^9.1.2
  connectivity_plus: ^5.0.2
  url_launcher: ^6.2.0
  video_player: ^2.8.2
  chewie: ^1.7.5
  image_picker: ^1.0.7
  shared_preferences: ^2.2.2
  barcode_scan2: ^4.3.0
  # image_gallery_saver: ^1.7.1
  # permission_handler: ^8.1.6

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
